name       : cntlm
version    : 0.92.3
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/cntlm/cntlm/cntlm%200.92.3/cntlm-0.92.3.tar.gz : 9c3ad10924d43f7248df9ecd33cbc033afbd7ea8d9545de0d68a2782fed76298
license    : GPL-2.0
summary    : Cntlm Authentication Proxy
description: |
    Cntlm (user-friendly wiki / technical manual) is an NTLM / NTLM Session Response / NTLMv2 authenticating HTTP proxy intended to help you break free from the chains of Microsoft proprietary world.
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
